version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=blocker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
